set_location_assignment PIN_AB12 -to i_A[0]
set_location_assignment PIN_AC12 -to i_A[1]
set_location_assignment PIN_AF9 -to i_A[2]
set_location_assignment PIN_AF10 -to i_A[3]
set_location_assignment PIN_AD11 -to i_B[0]
set_location_assignment PIN_AD12 -to i_B[1]
set_location_assignment PIN_AE11 -to i_B[2]
set_location_assignment PIN_AC9 -to i_B[3]
set_location_assignment PIN_AD10 -to i_C
set_location_assignment PIN_V16 -to o_SUM[0]
set_location_assignment PIN_W16 -to o_SUM[1]
set_location_assignment PIN_V17 -to o_SUM[2]
set_location_assignment PIN_V18 -to o_SUM[3]
set_location_assignment PIN_W17 -to o_C